[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["physics", "datasets", "models", "nsbi"]

[project]
name = "nsbi-tutorial"
version = "1.0.0"